version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env

  mongodb:
    image: mongo:6.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017"
    volumes:
      - ./data/db:/data/db

volumes:
  data:
